import type { Component } from "vue";
import {
  Archive,
  BarChart3,
  ChevronRight,
  Clock3,
  Database,
  Download,
  Ellipsis,
  FileCog,
  FileExclamationPoint,
  FilePlus2,
  Files,
  Folder,
  FolderCog,
  FolderLock,
  FolderPlus,
  FolderInput,
  History,
  Info,
  ListChecks,
  LogOut,
  PanelLeftClose,
  PanelLeftOpen,
  PencilLine,
  Search,
  Server,
  Settings2,
  Shapes,
  ShieldAlert,
  Star,
  Tags,
  Trash2,
  UserRound,
  Wrench,
  X,
} from "@lucide/vue";

export const appIcons = {
  archive: Archive,
  categories: Shapes,
  "chart-storage": BarChart3,
  "chevron-right": ChevronRight,
  clock: Clock3,
  collection: Archive,
  database: Database,
  download: Download,
  ellipsis: Ellipsis,
  file: Files,
  "file-maintenance": FileCog,
  "file-new": FilePlus2,
  "file-warning": FileExclamationPoint,
  folder: Folder,
  info: Info,
  "folder-maintenance": FolderCog,
  "folder-new": FolderPlus,
  "folder-protected": FolderLock,
  history: History,
  logout: LogOut,
  move: FolderInput,
  "panel-close": PanelLeftClose,
  "panel-open": PanelLeftOpen,
  rename: PencilLine,
  "risk-high": ShieldAlert,
  "risk-medium": Wrench,
  search: Search,
  server: Server,
  settings: Settings2,
  star: Star,
  tags: Tags,
  tasks: ListChecks,
  trash: Trash2,
  user: UserRound,
  x: X,
} satisfies Record<string, Component>;

export type AppIconName = keyof typeof appIcons;
