import type { Component } from "vue";
import {
  Archive,
  ArchiveRestore,
  AudioLines,
  ArrowDown,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowUp,
  ArrowUpDown,
  BarChart3,
  ChartPie,
  ChevronLeft,
  Cloud,
  CloudOff,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  Clock3,
  CircleAlert,
  CircleCheck,
  CirclePlay,
  CircleStop,
  CircleX,
  Copy,
  Container,
  Database,
  Download,
  Ellipsis,
  Eye,
  ExternalLink,
  EyeOff,
  FilterX,
  FileCog,
  FileExclamationPoint,
  FileArchive,
  FileCode,
  FileImage,
  FileMusic,
  FileSpreadsheet,
  FileText,
  FileType,
  FileVideoCamera,
  File,
  FilePlus2,
  FlipHorizontal2,
  Film,
  Folder,
  FolderCog,
  FolderLock,
  FolderPlus,
  FolderInput,
  History,
  Info,
  Grid2X2,
  Grid3X3,
  GripVertical,
  HardDrive,
  Heart,
  HeartOff,
  Home,
  List,
  ListChecks,
  LocateFixed,
  LoaderCircle,
  LogIn,
  LogOut,
  Maximize,
  Maximize2,
  Menu,
  MapPin,
  Minus,
  Minimize2,
  MoreVertical,
  Music2,
  PanelLeftClose,
  PanelLeftOpen,
  PencilLine,
  Pause,
  Play,
  Plus,
  Printer,
  RefreshCw,
  RotateCcw,
  RotateCw,
  ScanSearch,
  Search,
  Server,
  Share2,
  SkipBack,
  SkipForward,
  Settings2,
  Shapes,
  ShieldCheck,
  ShieldAlert,
  Sun,
  Star,
  SquareCheckBig,
  SquareTerminal,
  Tag,
  Tags,
  Text,
  Trash2,
  UserRound,
  UserPlus,
  Upload,
  Usb,
  Undo2,
  Volume2,
  VolumeOff,
  Wrench,
  X,
  Hourglass,
  ZoomIn,
  ZoomOut,
} from "@lucide/vue";

export const appIcons = {
  archive: Archive,
  "archive-restore": ArchiveRestore,
  "arrow-left": ArrowLeft,
  "arrow-left-right": ArrowLeftRight,
  "arrow-right": ArrowRight,
  "arrow-down": ArrowDown,
  "arrow-up": ArrowUp,
  "analysis-duplicates": Copy,
  "analysis-storage": ChartPie,
  analysis: ChartPie,
  categories: Shapes,
  cloud: Cloud,
  "cloud-off": CloudOff,
  "chart-storage": BarChart3,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-down": ChevronDown,
  "chevron-up": ChevronUp,
  clock: Clock3,
  "circle-check": CircleCheck,
  "circle-alert": CircleAlert,
  "circle-play": CirclePlay,
  "circle-stop": CircleStop,
  "circle-x": CircleX,
  collection: Archive,
  copy: Copy,
  container: Container,
  database: Database,
  download: Download,
  drag: GripVertical,
  ellipsis: Ellipsis,
  "external-link": ExternalLink,
  eye: Eye,
  "eye-off": EyeOff,
  file: File,
  "file-maintenance": FileCog,
  "file-archive": FileArchive,
  "file-code": FileCode,
  "file-image": FileImage,
  "file-music": FileMusic,
  "file-new": FilePlus2,
  "file-spreadsheet": FileSpreadsheet,
  "file-text": FileText,
  "file-type": FileType,
  "file-video": FileVideoCamera,
  "file-warning": FileExclamationPoint,
  flip: FlipHorizontal2,
  film: Film,
  "audio-lines": AudioLines,
  "filter-clear": FilterX,
  folder: Folder,
  info: Info,
  "folder-maintenance": FolderCog,
  "folder-new": FolderPlus,
  "folder-protected": FolderLock,
  history: History,
  "hard-drive": HardDrive,
  heart: Heart,
  "heart-off": HeartOff,
  home: Home,
  logout: LogOut,
  login: LogIn,
  loader: LoaderCircle,
  "locate-fixed": LocateFixed,
  "map-pin": MapPin,
  maximize: Maximize,
  "maximize-2": Maximize2,
  menu: Menu,
  music: Music2,
  minus: Minus,
  "minimize-2": Minimize2,
  more: MoreVertical,
  move: FolderInput,
  "panel-close": PanelLeftClose,
  "panel-open": PanelLeftOpen,
  rename: PencilLine,
  play: Play,
  pause: Pause,
  plus: Plus,
  printer: Printer,
  refresh: RefreshCw,
  retry: RotateCcw,
  "rotate-ccw": RotateCcw,
  "rotate-cw": RotateCw,
  "risk-high": ShieldAlert,
  "risk-medium": Wrench,
  search: Search,
  select: SquareCheckBig,
  scan: ScanSearch,
  server: Server,
  share: Share2,
  "skip-back": SkipBack,
  "skip-forward": SkipForward,
  settings: Settings2,
  "shield-check": ShieldCheck,
  sun: Sun,
  star: Star,
  tag: Tag,
  tags: Tags,
  text: Text,
  tasks: ListChecks,
  terminal: SquareTerminal,
  trash: Trash2,
  usb: Usb,
  user: UserRound,
  "user-add": UserPlus,
  upload: Upload,
  undo: Undo2,
  "volume-2": Volume2,
  "volume-off": VolumeOff,
  hourglass: Hourglass,
  "zoom-in": ZoomIn,
  "zoom-out": ZoomOut,
  sort: ArrowUpDown,
  "view-compact-grid": Grid3X3,
  "view-compact-list": List,
  "view-details": ListChecks,
  "view-mosaic": Grid2X2,
  x: X,
} satisfies Record<string, Component>;

export type AppIconName = keyof typeof appIcons;
