name: Docs

on:
  pull_request:
    paths:
      - "backend/www/**"
      - "*.md"
      - ".github/workflows/docs.yml"
  push:
    branches:
      - master

jobs:
  build:
    name: Build Docs
    if: github.event_name == 'pull_request' || vars.ENABLE_GITHUB_PAGES != 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Build site
        run: |
          docker build -f backend/www/Dockerfile -t filebrowser.site backend/www
          docker run --rm \
            -v "$GITHUB_WORKSPACE/backend/www:/docs" \
            -v "$GITHUB_WORKSPACE/LICENSE:/docs/docs/LICENSE:ro" \
            filebrowser.site build -d public

  build-and-release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master' && vars.ENABLE_GITHUB_PAGES == 'true'
    name: Build and Release Docs
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Build site
        run: |
          docker build -f backend/www/Dockerfile -t filebrowser.site backend/www
          docker run --rm \
            -v "$GITHUB_WORKSPACE/backend/www:/docs" \
            -v "$GITHUB_WORKSPACE/LICENSE:/docs/docs/LICENSE:ro" \
            filebrowser.site build -d public
      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: backend/www/public
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v5
